// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package letstalk is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	SignupRequest
	SignupReply
	LoginRequest
	LoginReply
	LogoutRequest
	LogoutReply
	CancelRequest
	CancelReply
	FollowRequest
	FollowReply
*/
package letstalk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignupRequest struct {
	Email     string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password1 string `protobuf:"bytes,2,opt,name=password1" json:"password1,omitempty"`
	Firstname string `protobuf:"bytes,3,opt,name=firstname" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,4,opt,name=lastname" json:"lastname,omitempty"`
}

func (m *SignupRequest) Reset()                    { *m = SignupRequest{} }
func (m *SignupRequest) String() string            { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()               {}
func (*SignupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword1() string {
	if m != nil {
		return m.Password1
	}
	return ""
}

func (m *SignupRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *SignupRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type SignupReply struct {
	Message   string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Sessionid string `protobuf:"bytes,2,opt,name=sessionid" json:"sessionid,omitempty"`
}

func (m *SignupReply) Reset()                    { *m = SignupReply{} }
func (m *SignupReply) String() string            { return proto.CompactTextString(m) }
func (*SignupReply) ProtoMessage()               {}
func (*SignupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignupReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SignupReply) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

type LoginRequest struct {
	Email     string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password1 string `protobuf:"bytes,2,opt,name=password1" json:"password1,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword1() string {
	if m != nil {
		return m.Password1
	}
	return ""
}

type LoginReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogoutRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogoutRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LogoutReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *LogoutReply) Reset()                    { *m = LogoutReply{} }
func (m *LogoutReply) String() string            { return proto.CompactTextString(m) }
func (*LogoutReply) ProtoMessage()               {}
func (*LogoutReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogoutReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CancelRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *CancelRequest) Reset()                    { *m = CancelRequest{} }
func (m *CancelRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()               {}
func (*CancelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CancelRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CancelReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *CancelReply) Reset()                    { *m = CancelReply{} }
func (m *CancelReply) String() string            { return proto.CompactTextString(m) }
func (*CancelReply) ProtoMessage()               {}
func (*CancelReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CancelReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FollowRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *FollowRequest) Reset()                    { *m = FollowRequest{} }
func (m *FollowRequest) String() string            { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()               {}
func (*FollowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FollowRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FollowReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *FollowReply) Reset()                    { *m = FollowReply{} }
func (m *FollowReply) String() string            { return proto.CompactTextString(m) }
func (*FollowReply) ProtoMessage()               {}
func (*FollowReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FollowReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "letstalk.SignupRequest")
	proto.RegisterType((*SignupReply)(nil), "letstalk.SignupReply")
	proto.RegisterType((*LoginRequest)(nil), "letstalk.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "letstalk.LoginReply")
	proto.RegisterType((*LogoutRequest)(nil), "letstalk.LogoutRequest")
	proto.RegisterType((*LogoutReply)(nil), "letstalk.LogoutReply")
	proto.RegisterType((*CancelRequest)(nil), "letstalk.CancelRequest")
	proto.RegisterType((*CancelReply)(nil), "letstalk.CancelReply")
	proto.RegisterType((*FollowRequest)(nil), "letstalk.FollowRequest")
	proto.RegisterType((*FollowReply)(nil), "letstalk.FollowReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Letstalk service

type LetstalkClient interface {
	// Sends a signup request
	SendSignup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error)
	// Sends a login request
	SendLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Sends a logout request
	SendLogout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error)
	// Sends a cancel request
	SendCancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelReply, error)
	// Sends a follow request
	SendFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowReply, error)
}

type letstalkClient struct {
	cc *grpc.ClientConn
}

func NewLetstalkClient(cc *grpc.ClientConn) LetstalkClient {
	return &letstalkClient{cc}
}

func (c *letstalkClient) SendSignup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error) {
	out := new(SignupReply)
	err := grpc.Invoke(ctx, "/letstalk.Letstalk/SendSignup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *letstalkClient) SendLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/letstalk.Letstalk/SendLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *letstalkClient) SendLogout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	out := new(LogoutReply)
	err := grpc.Invoke(ctx, "/letstalk.Letstalk/SendLogout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *letstalkClient) SendCancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelReply, error) {
	out := new(CancelReply)
	err := grpc.Invoke(ctx, "/letstalk.Letstalk/SendCancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *letstalkClient) SendFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowReply, error) {
	out := new(FollowReply)
	err := grpc.Invoke(ctx, "/letstalk.Letstalk/SendFollow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Letstalk service

type LetstalkServer interface {
	// Sends a signup request
	SendSignup(context.Context, *SignupRequest) (*SignupReply, error)
	// Sends a login request
	SendLogin(context.Context, *LoginRequest) (*LoginReply, error)
	// Sends a logout request
	SendLogout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// Sends a cancel request
	SendCancel(context.Context, *CancelRequest) (*CancelReply, error)
	// Sends a follow request
	SendFollow(context.Context, *FollowRequest) (*FollowReply, error)
}

func RegisterLetstalkServer(s *grpc.Server, srv LetstalkServer) {
	s.RegisterService(&_Letstalk_serviceDesc, srv)
}

func _Letstalk_SendSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetstalkServer).SendSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letstalk.Letstalk/SendSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetstalkServer).SendSignup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Letstalk_SendLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetstalkServer).SendLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letstalk.Letstalk/SendLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetstalkServer).SendLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Letstalk_SendLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetstalkServer).SendLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letstalk.Letstalk/SendLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetstalkServer).SendLogout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Letstalk_SendCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetstalkServer).SendCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letstalk.Letstalk/SendCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetstalkServer).SendCancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Letstalk_SendFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetstalkServer).SendFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letstalk.Letstalk/SendFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetstalkServer).SendFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Letstalk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "letstalk.Letstalk",
	HandlerType: (*LetstalkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSignup",
			Handler:    _Letstalk_SendSignup_Handler,
		},
		{
			MethodName: "SendLogin",
			Handler:    _Letstalk_SendLogin_Handler,
		},
		{
			MethodName: "SendLogout",
			Handler:    _Letstalk_SendLogout_Handler,
		},
		{
			MethodName: "SendCancel",
			Handler:    _Letstalk_SendCancel_Handler,
		},
		{
			MethodName: "SendFollow",
			Handler:    _Letstalk_SendFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4f, 0x84, 0x30,
	0x10, 0xdd, 0x5d, 0xbf, 0x60, 0xd6, 0xbd, 0x34, 0xab, 0x12, 0xe2, 0xc1, 0x34, 0xf1, 0xe3, 0x44,
	0xa2, 0x1e, 0x4d, 0x3c, 0x68, 0xf4, 0xc4, 0x69, 0xf7, 0x17, 0x54, 0xa9, 0xa4, 0xb1, 0xb4, 0x48,
	0x4b, 0x36, 0x7b, 0xf0, 0xf7, 0xf9, 0xb7, 0x0c, 0x94, 0x42, 0xc9, 0x26, 0x70, 0xd8, 0xe3, 0xcc,
	0x9b, 0xf7, 0x5e, 0x79, 0x33, 0x00, 0x94, 0x8a, 0x16, 0x51, 0x5e, 0x48, 0x2d, 0x91, 0xc7, 0xa9,
	0x56, 0x9a, 0xf0, 0x6f, 0xfc, 0x0b, 0x8b, 0x35, 0x4b, 0x45, 0x99, 0xaf, 0xe8, 0x4f, 0x49, 0x95,
	0x46, 0x4b, 0x38, 0xa2, 0x19, 0x61, 0x3c, 0x98, 0x5e, 0x4d, 0xef, 0xfc, 0x95, 0x29, 0xd0, 0x25,
	0xf8, 0x39, 0x51, 0x6a, 0x23, 0x8b, 0xe4, 0x3e, 0x98, 0xd5, 0x48, 0xd7, 0xa8, 0xd0, 0x2f, 0x56,
	0x28, 0x2d, 0x48, 0x46, 0x83, 0x03, 0x83, 0xb6, 0x0d, 0x14, 0x82, 0xc7, 0x49, 0x03, 0x1e, 0xd6,
	0x60, 0x5b, 0xe3, 0x37, 0x98, 0x5b, 0xfb, 0x9c, 0x6f, 0x51, 0x00, 0x27, 0x19, 0x55, 0x8a, 0xa4,
	0xb4, 0xb1, 0xb7, 0x65, 0x65, 0xa1, 0xa8, 0x52, 0x4c, 0x0a, 0x96, 0xd8, 0x07, 0xb4, 0x0d, 0xfc,
	0x02, 0xa7, 0xb1, 0x4c, 0x99, 0xd8, 0xe3, 0x23, 0xf0, 0x0d, 0x40, 0xa3, 0x31, 0xf8, 0x12, 0x7c,
	0x0d, 0x8b, 0x58, 0xa6, 0xb2, 0xd4, 0x83, 0x66, 0xf8, 0x16, 0xe6, 0x76, 0x6c, 0x54, 0xef, 0x95,
	0x88, 0x4f, 0xca, 0x47, 0xf5, 0xec, 0xd8, 0xa8, 0xde, 0xbb, 0xe4, 0x5c, 0x6e, 0x46, 0xf5, 0xec,
	0xd8, 0xa0, 0xde, 0xc3, 0xdf, 0x0c, 0xbc, 0xb8, 0x39, 0x17, 0xf4, 0x0c, 0xb0, 0xa6, 0x22, 0x31,
	0x3b, 0x43, 0x17, 0x91, 0xbd, 0xa3, 0xa8, 0x77, 0x44, 0xe1, 0xd9, 0x2e, 0x90, 0xf3, 0x2d, 0x9e,
	0xa0, 0x27, 0xf0, 0x2b, 0x7e, 0x1d, 0x34, 0x3a, 0xef, 0xa6, 0xdc, 0xed, 0x85, 0xcb, 0x9d, 0xbe,
	0x21, 0x37, 0xe6, 0x26, 0x56, 0xd7, 0xbc, 0xb7, 0x0f, 0xd7, 0xdc, 0xd9, 0x40, 0xc7, 0x37, 0x31,
	0xba, 0xfc, 0x5e, 0xfe, 0x2e, 0xdf, 0x49, 0xbc, 0xe3, 0x9b, 0xd8, 0x5c, 0x7e, 0x2f, 0x6f, 0x97,
	0xef, 0x24, 0x8c, 0x27, 0x1f, 0xc7, 0xf5, 0xcf, 0xf7, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0xc9, 0xc4, 0x2d, 0x8a, 0x03, 0x00, 0x00,
}
